version: '3'
services:
  mongo:
    image: mongo:4
    command: "--smallfiles"
    restart: always
    expose:
      - 27017

  mongo_test:
    image: mongo:4
    command: "--smallfiles"
    restart: always
    expose:
      - 27017

  api:
    image: node:8
    working_dir: /src
    command: sh -c "yarn && yarn start"
    ports:
      - "8080:8080"
    volumes:
      - ./api:/src
    environment:
      PATH: $PATH:/src/node_modules/.bin
      NODE_ENV: dev
      PORT: 8080
    restart: always
    links:
      - mongo

  api_test:
    image: node:8
    working_dir: /src
    command: sh -c "yarn"
    volumes:
      - ./api:/src:cached
    environment:
      PATH: $PATH:/src/node_modules/.bin
      NODE_ENV: test
    restart: always
    links:
      - mongo_test

  web:
    image: node:8
    working_dir: /src
    command: sh -c "yarn && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ./web:/src
    environment:
      PATH: $PATH:/src/node_modules/.bin
      NODE_ENV: dev
      PORT: 3000
    depends_on:
      - api
