version: '2'
services:
  mongo:
    image: mongo:3.3
    command: "--smallfiles"
    expose:
      - 27017

  api:
    image: node:6-wheezy
    working_dir: /src
    command: sh -c "npm install && npm start"
    ports:
      - "4040:4040"
    volumes:
      - ./api:/src
    environment:
      PATH: $PATH:/src/node_modules/.bin
      NODE_ENV: dev
      HTTP_SERVER_PORT: 4040
    links:
      - mongo

  web:
    image: node:6-wheezy
    working_dir: /src
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./web:/src
    environment:
      PATH: $PATH:/src/node_modules/.bin
      NODE_ENV: dev
      HTTP_SERVER_PORT: 3000
    depends_on:
      - api
